tablet desktop done
Hubert2113/Ice-Cream_projcet pull request #22
Opened 2021-12-11 14:42 UTC by wujt89

2021-12-11 15:41 UTC, Hubert2113 approved these changes

2021-12-11 15:42 UTC, Hubert2113 commented
jeszcze tylko scal maina do swojego brancha i mogę wrzucań na stronę

2021-12-11 22:09 UTC, dmjs23 requested changes
dlaczego usunąłeś całe linijki ścieżki zamiast samych poleceń "fill" w pliku sprite.svg ?
dodatkowo "margin-top: -60px;" w sekcji contakt nie zadziała a przynajmniej tak to u mnie wyszło jak sprawdziem.

2021-12-12 00:47 UTC, Hubert2113 requested changes
nie zauważyłem wcześniej tych błędów, popieram Kamila

2021-12-12 18:54 UTC, wujt89 commented
> dlaczego usunąłeś całe linijki ścieżki zamiast samych poleceń "fill" w pliku sprite.svg ? dodatkowo "margin-top: -60px;" w sekcji contakt nie zadziała a przynajmniej tak to u mnie wyszło jak sprawdziem. nazwa modifikatora " --loc " oraz "--fran" zmien prosze na całe nazwy bo teraz wiemy o co chodzi a w srode sie bedziemy zastanawiać co to jest.

Usunąłem ścieżki w svg, ponieważ były to ścieżki odnoszące się do tła a nie samej ikonki firmy. Zostały one po prostu źle pobrane według mnie razem z tłem z figmy a nie jako same ikonki. Nazwy oczywiście zaraz zmieniam a z tym marginem to się pobawie jak będzie górna sekcja zrobiona to wtedy naprawie. Dzięki za uwagi :)

2021-12-12 21:22 UTC, dmjs23 approved these changes
ta część teraz ok, co do marginesów to już możesz nad nimi pracować bo sekcja slidera jest skonczona i sie nie bedzie juz raczej zmieniac

2021-12-12 21:37 UTC, Hubert2113 approved these changes

2021-12-12 21:37 UTC, merged