poprawki
Hubert2113/Ice-Cream_projcet pull request #41
Opened 2021-12-20 19:40 UTC by wujt89

2021-12-20 20:46 UTC, Hubert2113 approved these changes

2021-12-20 21:26 UTC, Hubert2113 requested changes
widzę, że z jakiegoś powodu zdublowało ci się pare plików (obrazy, advantages.html i advantages.html
usuń je i jak dla mnie będzie ok

2021-12-21 11:59 UTC, Hubert2113 approved these changes

2021-12-21 19:34 UTC, dmjs23 approved these changes
ok

2021-12-22 08:59 UTC, AlbertGk approved these changes

2021-12-22 10:57 UTC, merged