Products
Hubert2113/Ice-Cream_projcet pull request #5
Opened 2021-12-09 15:00 UTC by MartaCzerniak

Wiem, że są niedociągnięcia. Będę jeszcze to poprawiać, ale na razie wyślę to, co mam.

2021-12-09 17:07 UTC, Hubert2113 commented on src/partials/products.html
> +
w plikach w folderze src/partials/ nie używamy <!doctype html>, tagów <html>, <head> ani <body>
ma być tam tylko zawartość <body>

2021-12-09 17:14 UTC, Hubert2113 commented on src/partials/products.html
> +<!DOCTYPE html>
w plikach w folderze src/partials/ nie używamy <!doctype html>, tagów , ani
ma być tam tylko zawartość

2021-12-09 23:51 UTC, dmjs23 requested changes
products.html nie moze posiadać całej struktury html jedynie kod sekcji którą tworzysz

2021-12-09 23:52 UTC, dmjs23 commented
dodatkowo przed ponownym wysłaniem sciągnij najnowszego maina i scal ze swoją gałęzią

2021-12-10 20:57 UTC, dmjs23 commented
kod wyglada dobrze, sciagnij najnowszego maina jak mówiliśmy i scal z gałęzią to bedzie mozna zrobic merge na głównego projektu

2021-12-10 20:57 UTC, dmjs23 reviewed
wyglada dobrze

2021-12-11 09:29 UTC, Hubert2113 approved these changes, later dismissed

2021-12-11 13:49 UTC, merged