okno modalne
Hubert2113/Ice-Cream_projcet pull request #6
Opened 2021-12-09 16:19 UTC by PiotrekHadziewicz

2021-12-09 17:28 UTC, Hubert2113 commented on src/partials/modal.html
> +  <use href="#icon-burger"></use>
plik svg powinien pochodzić ze sprite

2021-12-09 17:38 UTC, PiotrekHadziewicz commented on src/partials/modal.html
> +  <use href="#icon-burger"></use>
xd zapomniałem usunąć

2021-12-09 19:50 UTC, dmjs23 commented on src/partials/modal.html
> +  <use href="#icon-burger"></use>
modal powinno być zamknięte w nadrzędny div

2021-12-09 20:00 UTC, Hubert2113 approved these changes

2021-12-09 23:41 UTC, dmjs23 requested changes
<svg class="modal-menu-open" data-mobile-menu-open>
  <use href="../images/sprite.svg#icon-burger"></use>
</svg>

tak jak mówiliśmy tego nie powinno być w twoim kodzie w pliku modal.html

2021-12-10 11:27 UTC, Hubert2113 approved these changes

2021-12-10 11:27 UTC, Hubert2113 commented on src/partials/modal.html
> +</svg>
Kamil ma racje, moim zdaniem zostaw kwestie przycisku dla Ablerta, nazwe zmiennej weźmie z twojego kodu

2021-12-10 11:37 UTC, merged